#!/bin/bash

if ! test "$(ls -A "/var/database")"; then
    if [ ! -d "/var/databaselogs/mysql" ]; then
      mkdir /var/databaselogs/mysql
    fi
    chown -R mysql:mysql /var/database
    chown -R mysql:mysql /var/databaselogs
    
    mysql_install_db
    
    chown -R mysql:mysql /var/database
    
    # Create a user called admin for remote access
    /usr/bin/mysqld_safe > /dev/null 2>&1 &
    RET=1
    while [[ RET -ne 0 ]]; do
	    sleep 5
	    mysql -uroot -e "status" > /dev/null 2>&1
	    RET=$?
    done
    
    # Import the initial database
    mysql -uroot -e "CREATE SCHEMA Skynet;"
    mysql -uroot -DSkynet < /root/initialdb.sql
    
    # Create a user for PressGang to use
    mysql -uroot -e "CREATE USER 'admin'@'localhost' IDENTIFIED BY 'mariadb'"
    mysql -uroot -e "GRANT ALL PRIVILEGES ON Skynet.* TO 'admin'@'%' WITH GRANT OPTION"

    mysqladmin -uroot shutdown       
fi

touch /var/database/.processed