#!/bin/bash
# Delays the execution of a program until a mariadb is available
RET=1
while [[ RET -ne 0 ]]; do
  echo "Sleeping for 5 seconds waiting for MariaDB"
  sleep 5
  mysql -uroot -e "status" > /dev/null 2>&1
  RET=$?
done

COMMAND=$1
shift
${COMMAND} "$@"